# Generated by Django 5.2.3 on 2025-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dispositivo_ultima_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/dispositivos'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/equipamentos'),
        ),
        migrations.AddField(
            model_name='estoqueveiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos'),
        ),
    ]
