# Generated by Django 5.2.3 on 2025-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dispositivoseguranca_equipamento_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivoseguranca',
            name='local_instalacao',
        ),
        migrations.AddField(
            model_name='dispositivoseguranca',
            name='localizacao',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('POSTO_AVANCADO', 'Posto Avançado'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria')], default='CENTRO', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='localizacao',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('POSTO_AVANCADO', 'Posto Avançado'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria')], default='CENTRO', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('gerente', 'Gerente'), ('administrador', 'Administrador'), ('batman', 'Batman')], default='funcionario', max_length=20),
        ),
    ]
