# Generated by Django 5.2.3 on 2025-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dispositivoseguranca_local_instalacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoseguranca',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('funcionario', 'Funcionário'), ('gerente', 'Gerente'), ('administrador', 'Administrador'), ('batman', 'Batman'), ('alfred', 'Alfred')], default='funcionario', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivoseguranca',
            name='localizacao',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='localizacao',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=30),
        ),
    ]
