# Generated by Django 5.2.3 on 2025-07-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dispositivo_imagem_equipamento_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueveiculo',
            name='imagem',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='dispositivos'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos'),
        ),
    ]
