# Generated by Django 5.2.3 on 2025-07-11 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estoqueveiculo_imagem_veiculo_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dispositivo', 'Dispositivo'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('item_nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('local_origem', models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=30)),
                ('local_destino', models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
