# Generated by Django 5.2.3 on 2025-07-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dispositivoseguranca_secret_equipamento_secret_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DispositivoSeguranca',
            new_name='Dispositivo',
        ),
    ]
