# Generated by Django 5.2.3 on 2025-07-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_dispositivoseguranca_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
