# Generated by Django 5.2.3 on 2025-07-11 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requisicaomovimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicaomovimentacao',
            old_name='autorizado_por',
            new_name='autorizador',
        ),
        migrations.RenameField(
            model_name='requisicaomovimentacao',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='requisicaomovimentacao',
            old_name='item_nome',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='requisicaomovimentacao',
            old_name='tipo',
            new_name='tipo_item',
        ),
        migrations.RemoveField(
            model_name='requisicaomovimentacao',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='requisicaomovimentacao',
            name='local_destino',
        ),
        migrations.RemoveField(
            model_name='requisicaomovimentacao',
            name='local_origem',
        ),
        migrations.RemoveField(
            model_name='requisicaomovimentacao',
            name='status',
        ),
        migrations.AddField(
            model_name='requisicaomovimentacao',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaomovimentacao',
            name='origem',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicaomovimentacao',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
