# Generated by Django 5.2.3 on 2025-07-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_autorizado_por_requisicaomovimentacao_autorizador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaomovimentacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20),
        ),
    ]
