# Generated by Django 5.2.3 on 2025-07-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dispositivo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
