# Generated by Django 5.2.3 on 2025-07-14 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requisicaomovimentacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('dispositivo', 'Dispositivo'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('destino', models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('negada', 'Negada'), ('convertida', 'Convertida em Ordem de Compra')], default='pendente', max_length=20)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('dispositivo', 'Dispositivo'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('destino', models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=50)),
                ('status', models.CharField(choices=[('autorizada', 'Autorizada'), ('paga', 'Paga'), ('negada', 'Negada')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_pagas', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solicitacaocompra')),
            ],
        ),
    ]
