# Generated by Django 5.2.3 on 2025-07-01 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dispositivo_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='data_aquisicao',
            new_name='ultima_manutencao',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ultima_manutencao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
