# Generated by Django 5.2.3 on 2025-07-15 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitacaocompra_ordemcompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('dispositivo', 'Dispositivo'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('localizacao', models.CharField(choices=[('CENTRO', 'Centro'), ('WEST_TOWN', 'West Town'), ('DOWN_TOWN', 'Down Town'), ('PORTO', 'Porto'), ('AEROPORTO', 'Aeroporto'), ('GALPAO_NORTE', 'Galpão Norte'), ('SEDE_DA_INDUSTRIA', 'Sede da Indústria'), ('BAT_CAVERNA', 'Bat Caverna'), ('POSTO_AVANCADO_CENTRO', 'Posto Avançado Centro'), ('POSTO_AVANCADO_NORTE', 'Posto Avançado Norte'), ('ESTACAO_SUBMERSA_PORTO', 'Estação Submersa Porto')], max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('negada', 'Negada'), ('em_manutencao', 'Em Manutenção'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
